server:
  port: ${ORDER_SERVICE_PORT:8081}

spring:
  application:
    name: order-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/order_service}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:${EUREKA_PORT:8761}/eureka/
