server:
  port: ${INVENTORY_SERVICE_PORT:8082}

spring:
  application:
    name: inventory-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/inventory_service}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:${EUREKA_PORT:8761}/eureka/
